name: Docker Build and Push

on:
  push:
    branches: [ "main" ]

# GitHub Container Registry'ye (GHCR) imaj yükleyebilmek için yazma yetkisi veriyoruz
permissions:
  packages: write
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Klonla
        uses: actions/checkout@v4

      - name: GitHub Container Registry'ye Giriş Yap
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker İmajını Derle ve Yükle
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # İmajın adını belirliyoruz. Tüm harfler küçük olmalı!
          tags: ghcr.io/sweiznn/gh-deployment-workflow:latest

  deploy-to-ec2:
    needs: build   # Burası ilk baştaki 'build:' adımıyla tamamen aynı yapıldı
    runs-on: ubuntu-latest
    steps:
      - name: EC2'ye Bağlan ve Deploy Et
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Çalışan eski container'ı durdur ve sil (İlk kurulumda hata vermemesi için || true ekliyoruz)
            docker stop web-site || true
            docker rm web-site || true
            
            # Güncellenmiş en yeni imajı indir
            docker pull ghcr.io/sweiznn/gh-deployment-workflow:latest
            
            # Yeni imajı 80 portunda arka planda çalıştır
            docker run -d --name web-site -p 9090:80 ghcr.io/sweiznn/gh-deployment-workflow:latest
